baseURL = "/next/"
languageCode = "en-us"
title = "Exploring the Cold War"

[params]
    titleShort = "Cold War"

[[menu.main]]
    name = "Political"
    url = "/political/"

[[menu.main]]
    name = "Social"
    url = "/social/"