baseURL = "http://example.org/"
languageCode = "en-us"
title = "Exploring the Cold War"

[params]
    titleShort = "Cold War"

[[menu.main]]
    name = "Political"
    url = "/categoties/political/"

[[menu.main]]
    name = "Social"
    url = "/categories/social/"